services:
  # ecommerce:
  #   build: ./application
  #   ports:
  #     - 4000:3000
  #   volumes:
  #     - ./application:/app

  database:
    image: postgres:latest
    environment:
      - "POSTGRES_PASSWORD=Postgres2022!"
      - "POSTGRES_USER=root"
      - "POSTGRES_DB=ecommerce"
    ports:
      - 5000:5432
    volumes:
      - data:/var/lib/postgresql/data
volumes:
  data: